quorum_sizes:
  read: 2
  write: 3
nodes:
  - id: node1
    ip: localhost
    port: 32770
    weight: 1
  - id: node2
    ip: localhost
    port: 32771
    weight: 2
  - id: node3
    ip: localhost
    port: 32772
    weight: 1